import { describe, expect, it } from 'vitest';
import { expectConsoleMessages } from '@/tests/helpers/expected-console';
import { generateSceneOutlinesFromRequirements } from '@/lib/generation/outline-generator';
import { generateSceneContent } from '@/lib/generation/scene-generator';
import { buildPrompt, PROMPT_IDS } from '@/lib/prompts';
import { buildPromptWithSkill } from '@/lib/skills/prompt-overrides';
import type { AICallFn } from '@/lib/generation/pipeline-types';
import type { SceneOutline, UserRequirements } from '@/lib/types/generation';

const SKILL_ID = 'formation-design-pro';
const OVERRIDE_SENTINEL = 'Formation Engine Platform Publication — Evidence-Gated Andragogy';

describe('skill prompt wiring', () => {
  const requirements: UserRequirements = {
    requirement: 'Former des responsables aux entretiens difficiles',
    activeSkillId: SKILL_ID,
  };

  it('changes both outline and scene prompts when the skill engine is enabled', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };

    await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: true },
    );

    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify({ elements: [], background: null, remark: '' });
    };
    const outline: SceneOutline = {
      id: 'scene-1',
      type: 'slide',
      title: 'Conduire l’entretien',
      description: 'Une mise en situation professionnelle.',
      keyPoints: ['Préparer', 'Écouter', 'Conclure'],
      order: 1,
    };

    await generateSceneContent(outline, sceneCall, {
      skillEngineEnabled: true,
      activeSkillId: SKILL_ID,
    });

    expect(outlineSystem).toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).toContain(OVERRIDE_SENTINEL);
  });

  it('changes the observable outline generated by a model that follows the engine contract', async () => {
    const responsiveModel: AICallFn = async (system) =>
      JSON.stringify({
        languageDirective: 'Répondre en français.',
        outlines: [
          {
            id: 'observable',
            type: 'slide',
            title: system.includes(OVERRIDE_SENTINEL)
              ? 'Performance, activité et preuve alignées'
              : 'Présentation générale',
            description: 'Résultat observable du contrat système.',
            keyPoints: ['Point vérifiable'],
            order: 1,
          },
        ],
      });

    const enabled = await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      responsiveModel,
      undefined,
      { skillEngineEnabled: true },
    );
    const disabled = await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      responsiveModel,
      undefined,
      { skillEngineEnabled: false },
    );

    expect(enabled.data?.outlines[0]?.title).toBe('Performance, activité et preuve alignées');
    expect(disabled.data?.outlines[0]?.title).toBe('Présentation générale');
  });

  it('applies the formation engine when no optional domain skill is selected', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };

    await generateSceneOutlinesFromRequirements(
      { requirement: 'Former des responsables aux entretiens difficiles' },
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: true },
    );

    expect(outlineSystem).toContain(OVERRIDE_SENTINEL);
  });

  it('composes the core formation engine before an optional domain skill', async () => {
    expectConsoleMessages({
      warn: [
        '[WARN] [Generation] Quiz question count rejected for quiz-1: Return exactly 3 complete quiz questions; the rejected response contained 0.',
      ],
    });
    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify([]);
    };

    await generateSceneContent(
      {
        id: 'quiz-1',
        type: 'quiz',
        title: 'Revue de code',
        description: 'Choisir une correction.',
        keyPoints: ['Identifier le défaut'],
        order: 1,
      },
      sceneCall,
      { skillEngineEnabled: true, activeSkillId: 'coding-workshop' },
    );

    expect(sceneSystem).toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).toContain('trouver le bug');
    expect(sceneSystem.indexOf(OVERRIDE_SENTINEL)).toBeLessThan(
      sceneSystem.indexOf('trouver le bug'),
    );
  });

  it('keeps both prompts unchanged when the skill engine is disabled', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };
    await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: false },
    );

    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify({ elements: [], background: null, remark: '' });
    };
    await generateSceneContent(
      {
        id: 'scene-1',
        type: 'slide',
        title: 'Conduire l’entretien',
        description: 'Une mise en situation professionnelle.',
        keyPoints: ['Préparer'],
        order: 1,
      },
      sceneCall,
      { skillEngineEnabled: false, activeSkillId: SKILL_ID },
    );

    expect(outlineSystem).not.toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).not.toContain(OVERRIDE_SENTINEL);
  });

  it('keeps the assembled outline and scene prompts byte-for-byte identical when disabled', () => {
    const promptCases = [
      {
        id: PROMPT_IDS.REQUIREMENTS_TO_OUTLINES,
        variables: {
          requirement: requirements.requirement,
          pdfContent: 'None',
          availableImages: 'No images available',
          userProfile: '',
          hasSourceImages: false,
          imageEnabled: false,
          videoEnabled: false,
          mediaEnabled: false,
          researchContext: 'None',
          availablePlugins: '',
          hasPlugins: false,
          teacherContext: '',
        },
      },
      {
        id: PROMPT_IDS.SLIDE_CONTENT,
        variables: {
          title: 'Conduire l’entretien',
          description: 'Une mise en situation professionnelle.',
          keyPoints: '1. Préparer',
          elements: '',
          assignedImages: 'No images available',
          canvas_width: 1000,
          canvas_height: 562.5,
          teacherContext: '',
          languageDirective: 'Répondre en français.',
          imageElementEnabled: false,
          generatedImageEnabled: false,
          generatedVideoEnabled: false,
          mediaElementEnabled: false,
        },
      },
    ];

    for (const { id, variables } of promptCases) {
      expect(
        buildPromptWithSkill(id, variables, {
          enabled: false,
          activeSkillId: SKILL_ID,
        }),
      ).toEqual(buildPrompt(id, variables));
    }
  });
});
