import { describe, expect, it } from 'vitest';
import { generateSceneOutlinesFromRequirements } from '@/lib/generation/outline-generator';
import { generateSceneContent } from '@/lib/generation/scene-generator';
import type { AICallFn } from '@/lib/generation/pipeline-types';
import type { SceneOutline, UserRequirements } from '@/lib/types/generation';

const SKILL_ID = 'formation-design-pro';
const OVERRIDE_SENTINEL = 'Formation Engine Platform Publication — Evidence-Gated Andragogy';

describe('skill prompt wiring', () => {
  const requirements: UserRequirements = {
    requirement: 'Former des responsables aux entretiens difficiles',
    activeSkillId: SKILL_ID,
  };

  it('changes both outline and scene prompts when the skill engine is enabled', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };

    await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: true },
    );

    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify({ elements: [], background: null, remark: '' });
    };
    const outline: SceneOutline = {
      id: 'scene-1',
      type: 'slide',
      title: 'Conduire l’entretien',
      description: 'Une mise en situation professionnelle.',
      keyPoints: ['Préparer', 'Écouter', 'Conclure'],
      order: 1,
    };

    await generateSceneContent(outline, sceneCall, {
      skillEngineEnabled: true,
      activeSkillId: SKILL_ID,
    });

    expect(outlineSystem).toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).toContain(OVERRIDE_SENTINEL);
  });

  it('changes the observable outline generated by a model that follows the engine contract', async () => {
    const responsiveModel: AICallFn = async (system) =>
      JSON.stringify({
        languageDirective: 'Répondre en français.',
        outlines: [
          {
            id: 'observable',
            type: 'slide',
            title: system.includes(OVERRIDE_SENTINEL)
              ? 'Performance, activité et preuve alignées'
              : 'Présentation générale',
            description: 'Résultat observable du contrat système.',
            keyPoints: ['Point vérifiable'],
            order: 1,
          },
        ],
      });

    const enabled = await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      responsiveModel,
      undefined,
      { skillEngineEnabled: true },
    );
    const disabled = await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      responsiveModel,
      undefined,
      { skillEngineEnabled: false },
    );

    expect(enabled.data?.outlines[0]?.title).toBe('Performance, activité et preuve alignées');
    expect(disabled.data?.outlines[0]?.title).toBe('Présentation générale');
  });

  it('applies the formation engine when no optional domain skill is selected', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };

    await generateSceneOutlinesFromRequirements(
      { requirement: 'Former des responsables aux entretiens difficiles' },
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: true },
    );

    expect(outlineSystem).toContain(OVERRIDE_SENTINEL);
  });

  it('composes the core formation engine before an optional domain skill', async () => {
    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify([]);
    };

    await generateSceneContent(
      {
        id: 'quiz-1',
        type: 'quiz',
        title: 'Revue de code',
        description: 'Choisir une correction.',
        keyPoints: ['Identifier le défaut'],
        order: 1,
      },
      sceneCall,
      { skillEngineEnabled: true, activeSkillId: 'coding-workshop' },
    );

    expect(sceneSystem).toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).toContain('trouver le bug');
    expect(sceneSystem.indexOf(OVERRIDE_SENTINEL)).toBeLessThan(
      sceneSystem.indexOf('trouver le bug'),
    );
  });

  it('keeps both prompts unchanged when the skill engine is disabled', async () => {
    let outlineSystem = '';
    const outlineCall: AICallFn = async (system) => {
      outlineSystem = system;
      return JSON.stringify({ languageDirective: 'Répondre en français.', outlines: [] });
    };
    await generateSceneOutlinesFromRequirements(
      requirements,
      undefined,
      undefined,
      outlineCall,
      undefined,
      { skillEngineEnabled: false },
    );

    let sceneSystem = '';
    const sceneCall: AICallFn = async (system) => {
      sceneSystem = system;
      return JSON.stringify({ elements: [], background: null, remark: '' });
    };
    await generateSceneContent(
      {
        id: 'scene-1',
        type: 'slide',
        title: 'Conduire l’entretien',
        description: 'Une mise en situation professionnelle.',
        keyPoints: ['Préparer'],
        order: 1,
      },
      sceneCall,
      { skillEngineEnabled: false, activeSkillId: SKILL_ID },
    );

    expect(outlineSystem).not.toContain(OVERRIDE_SENTINEL);
    expect(sceneSystem).not.toContain(OVERRIDE_SENTINEL);
  });
});
