import { beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';

const mocks = vi.hoisted(() => ({
  requireSuperAdmin: vi.fn(),
  resolveModel: vi.fn(),
  callLLM: vi.fn(),
}));

vi.mock('@/lib/api/auth', () => ({ requireSuperAdmin: mocks.requireSuperAdmin }));
vi.mock('@/lib/server/resolve-model', () => ({ resolveModel: mocks.resolveModel }));
vi.mock('@/lib/ai/llm', () => ({ callLLM: mocks.callLLM }));

import { POST } from '@/app/api/admin/widget-templates/generate/route';

const composition = {
  version: 1,
  locale: 'fr-FR',
  direction: 'ltr',
  title: 'Calcul simple',
  inputs: [],
  computations: [{ id: 'total', label: 'Total', expression: { op: 'literal', value: 42 } }],
  nodes: [{ id: 'result', type: 'computed_value', computationId: 'total' }],
  rootNodeIds: ['result'],
  goldenCases: [{ name: 'cas nominal', inputs: {}, expected: { total: 42 } }],
};

function request(body: unknown): NextRequest {
  return new NextRequest('https://qalem.ma/api/admin/widget-templates/generate', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-model': 'attacker:unmanaged-model',
      'x-base-url': 'https://attacker.invalid/v1',
    },
    body: JSON.stringify(body),
  });
}

describe('super-admin widget generation route (S6-028)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.requireSuperAdmin.mockResolvedValue({
      user: { id: '00000000-0000-4000-8000-000000000001', email: 'root@qalem.ma' },
    });
    mocks.resolveModel.mockResolvedValue({
      model: { provider: 'managed' },
      modelInfo: {},
      modelString: 'managed:configured-model',
      providerId: 'managed',
      modelId: 'configured-model',
      apiKey: 'server-owned',
    });
    mocks.callLLM.mockResolvedValue({ text: JSON.stringify(composition) });
  });

  it('returns a fully validated composition generated by the administered model', async () => {
    const response = await POST(
      request({
        request: 'Crée un widget qui affiche la réponse à un calcul simple.',
        locale: 'fr-FR',
      }),
    );
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.composition).toEqual(composition);
    expect(mocks.resolveModel).toHaveBeenCalledWith({ stage: 'widget-composition' });
    expect(mocks.callLLM).toHaveBeenCalledOnce();
    expect(mocks.callLLM.mock.calls[0]?.[0]).not.toHaveProperty('output');
  });

  it('rejects tenant administrators before resolving or calling a model', async () => {
    mocks.requireSuperAdmin.mockResolvedValue({ response: new Response(null, { status: 403 }) });

    const response = await POST(
      request({
        request: 'Crée un widget qui affiche la réponse à un calcul simple.',
        locale: 'fr-FR',
      }),
    );

    expect(response.status).toBe(403);
    expect(mocks.resolveModel).not.toHaveBeenCalled();
    expect(mocks.callLLM).not.toHaveBeenCalled();
  });

  it.each([
    { request: '', locale: 'fr-FR' },
    { request: 'trop court', locale: 'fr-FR' },
    { request: 'x'.repeat(4_001), locale: 'fr-FR' },
    { request: 'Crée un widget de calcul valide et pédagogique.', locale: 'de-DE' },
  ])('rejects an invalid generation request: %o', async (input) => {
    const response = await POST(request(input));

    expect(response.status).toBe(400);
    expect(mocks.resolveModel).not.toHaveBeenCalled();
    expect(mocks.callLLM).not.toHaveBeenCalled();
  });

  it('rejects a generated composition whose golden cases fail', async () => {
    mocks.callLLM.mockResolvedValue({
      text: JSON.stringify({
        ...composition,
        goldenCases: [{ name: 'cas corrompu', inputs: {}, expected: { total: 41 } }],
      }),
    });

    const response = await POST(
      request({
        request: 'Crée un widget qui affiche la réponse à un calcul simple.',
        locale: 'fr-FR',
      }),
    );
    const body = await response.json();

    expect(response.status).toBe(502);
    expect(body.errorCode).toBe('PARSE_FAILED');
    expect(body.composition).toBeUndefined();
  });

  it('rejects a composition generated for a different locale or direction', async () => {
    mocks.callLLM.mockResolvedValue({
      text: JSON.stringify({ ...composition, locale: 'en-US', direction: 'rtl' }),
    });

    const response = await POST(
      request({
        request: 'Crée un widget qui affiche la réponse à un calcul simple.',
        locale: 'fr-FR',
      }),
    );

    expect(response.status).toBe(502);
  });
});
