'use client';

import { useState, useCallback, useEffect } from 'react';
import { Award, Download, Linkedin, Link2, Check, X, Loader2 } from 'lucide-react';
import { useI18n } from '@/lib/hooks/use-i18n';
import { useAuth } from '@/lib/hooks/use-auth';
import { cn } from '@/lib/utils';
import type { Certificate } from '@/lib/certificates/types';

// ---------------------------------------------------------------------------
// Local storage helpers for guest certificates
// ---------------------------------------------------------------------------

const GUEST_CERTS_KEY = 'qalem-guest-certificates';

interface GuestCertificateData {
  certificate: Certificate & { completionDate: string };
  html: string;
}

function loadGuestCertificates(): GuestCertificateData[] {
  try {
    const raw = localStorage.getItem(GUEST_CERTS_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function saveGuestCertificate(data: GuestCertificateData): void {
  try {
    const existing = loadGuestCertificates();
    const filtered = existing.filter(
      (c) => c.certificate.stageId !== data.certificate.stageId,
    );
    filtered.push(data);
    localStorage.setItem(GUEST_CERTS_KEY, JSON.stringify(filtered));
  } catch {
    // localStorage unavailable
  }
}

function findGuestCertificate(stageId: string): GuestCertificateData | undefined {
  return loadGuestCertificates().find((c) => c.certificate.stageId === stageId);
}

export { loadGuestCertificates, type GuestCertificateData };

// ---------------------------------------------------------------------------
// Certificate Modal
// ---------------------------------------------------------------------------

function CertificateModal({
  html,
  verificationUrl,
  courseName,
  onClose,
}: {
  html: string;
  verificationUrl: string;
  courseName: string;
  onClose: () => void;
}): React.ReactElement {
  const { t } = useI18n();
  const [linkCopied, setLinkCopied] = useState(false);

  const handleDownload = useCallback(() => {
    // Open certificate HTML in a new window for printing
    const win = window.open('', '_blank');
    if (win) {
      win.document.write(html);
      win.document.close();
      // Wait for fonts/images to load before triggering print
      win.onload = () => {
        setTimeout(() => win.print(), 500);
      };
    }
  }, [html]);

  const handleLinkedIn = useCallback(() => {
    const shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(verificationUrl)}`;
    window.open(shareUrl, '_blank', 'noopener,noreferrer');
  }, [verificationUrl]);

  const handleCopyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(verificationUrl);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    } catch {
      // Fallback for browsers without clipboard API
      const input = document.createElement('input');
      input.value = verificationUrl;
      document.body.appendChild(input);
      input.select();
      document.execCommand('copy');
      document.body.removeChild(input);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    }
  }, [verificationUrl]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Overlay */}
      <div
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative z-10 w-[900px] max-w-[95vw] max-h-[90vh] bg-white dark:bg-gray-900 rounded-2xl shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-700">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            {courseName}
          </h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            <X className="size-5" />
          </button>
        </div>

        {/* Certificate HTML preview
            SAFETY: The HTML is generated by our own renderCertificateHTML() which
            escapes all dynamic values via escapeHtml(). No user-supplied raw HTML
            is ever injected — the template is fully server/lib-controlled. */}
        <div className="flex-1 overflow-auto p-4 bg-gray-50 dark:bg-gray-950">
          <div
            className="mx-auto"
            // SAFETY: trusted HTML from renderCertificateHTML (all dynamic values escaped via escapeHtml)
            dangerouslySetInnerHTML={{ __html: html }}
          />
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-3 px-6 py-4 border-t border-gray-200 dark:border-gray-700">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium transition-colors"
          >
            <Download className="size-4" />
            {t('certificate.download')}
          </button>
          <button
            onClick={handleLinkedIn}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium transition-colors"
          >
            <Linkedin className="size-4" />
            {t('certificate.share')}
          </button>
          <button
            onClick={handleCopyLink}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium transition-colors"
          >
            {linkCopied ? (
              <>
                <Check className="size-4 text-green-600" />
                {t('certificate.linkCopied')}
              </>
            ) : (
              <>
                <Link2 className="size-4" />
                {t('certificate.copyLink')}
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

export { CertificateModal };

// ---------------------------------------------------------------------------
// Certificate Prompt Banner — shown in classroom when course is complete
// ---------------------------------------------------------------------------

interface CertificatePromptProps {
  stageId: string;
  allScenesCompleted: boolean;
  quizScores: number[]; // Array of quiz scores (0-100). Empty if no quizzes.
}

export function CertificatePrompt({
  stageId,
  allScenesCompleted,
  quizScores,
}: CertificatePromptProps): React.ReactElement | null {
  const { t, locale } = useI18n();
  const { isGuest } = useAuth();
  const [loading, setLoading] = useState(false);
  const [certHtml, setCertHtml] = useState<string | null>(null);
  const [certData, setCertData] = useState<Certificate | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [hasExisting, setHasExisting] = useState(false);

  // Check if average quiz score meets threshold
  const avgScore =
    quizScores.length > 0
      ? quizScores.reduce((sum, s) => sum + s, 0) / quizScores.length
      : 100; // No quizzes = auto-pass

  const meetsThreshold = avgScore >= 60;
  const shouldShow = allScenesCompleted && meetsThreshold;

  // Check for existing guest certificate
  /* eslint-disable react-hooks/set-state-in-effect -- Load cached guest certificate on mount */
  useEffect(() => {
    if (isGuest && stageId) {
      const existing = findGuestCertificate(stageId);
      if (existing) {
        setHasExisting(true);
        setCertHtml(existing.html);
        setCertData({
          ...existing.certificate,
          completionDate: new Date(existing.certificate.completionDate),
        });
      }
    }
  }, [isGuest, stageId]);
  /* eslint-enable react-hooks/set-state-in-effect */

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/certificates/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ stageId }),
      });

      const json = await res.json();

      if (json.success && json.data?.certificate) {
        const cert = json.data.certificate as Certificate;
        cert.completionDate = new Date(cert.completionDate);
        setCertData(cert);
        setHasExisting(true);

        // Render the certificate HTML client-side
        const { renderCertificateHTML } = await import('@/lib/certificates/generator');
        const html = renderCertificateHTML(cert, locale);
        setCertHtml(html);

        // For guests, store in localStorage
        if (isGuest) {
          saveGuestCertificate({
            certificate: {
              ...cert,
              completionDate: cert.completionDate.toISOString(),
            } as Certificate & { completionDate: string },
            html,
          });
        }

        setShowModal(true);
      }
    } catch (error) {
      console.error('Failed to generate certificate:', error);
    } finally {
      setLoading(false);
    }
  }, [stageId, isGuest, locale]);

  const handleView = useCallback(async () => {
    if (certHtml) {
      setShowModal(true);
      return;
    }
    // Re-fetch if we don't have HTML
    await handleGenerate();
  }, [certHtml, handleGenerate]);

  if (!shouldShow) return null;

  return (
    <>
      {/* Banner */}
      <div className="mx-4 mb-3 rounded-xl bg-gradient-to-r from-purple-50 to-violet-50 dark:from-purple-950/30 dark:to-violet-950/30 border border-purple-200/60 dark:border-purple-800/40 p-4">
        <div className="flex items-center gap-4">
          {/* Icon */}
          <div className="shrink-0 w-10 h-10 rounded-full bg-purple-100 dark:bg-purple-900/40 flex items-center justify-center">
            <Award className="size-5 text-purple-600 dark:text-purple-400" />
          </div>

          {/* Text */}
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-purple-900 dark:text-purple-100">
              {t('certificate.congratulations')} {t('certificate.courseCompleted')}
            </p>
          </div>

          {/* Button */}
          <button
            onClick={hasExisting ? handleView : handleGenerate}
            disabled={loading}
            className={cn(
              'shrink-0 flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors',
              'bg-purple-600 hover:bg-purple-700 text-white',
              'disabled:opacity-50 disabled:cursor-not-allowed',
            )}
          >
            {loading ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Award className="size-4" />
            )}
            {hasExisting
              ? t('certificate.viewCertificate')
              : t('certificate.getCertificate')}
          </button>
        </div>
      </div>

      {/* Modal */}
      {showModal && certHtml && certData && (
        <CertificateModal
          html={certHtml}
          verificationUrl={certData.verificationUrl}
          courseName={certData.courseName}
          onClose={() => setShowModal(false)}
        />
      )}
    </>
  );
}
